import { createDefaultBrushDraft } from "../domain/tiles/brushDraft.js";
import { createGlobalHistoryTimelineState } from "../domain/history/globalTimeline.js";
import { createInitialAssetManagerWizardState } from "../domain/assets/assetManagerWizardModel.js";
import { DEFAULT_NEW_LEVEL_HEIGHT, DEFAULT_NEW_LEVEL_WIDTH } from "../data/createNewLevelDocument.js";
import { DEFAULT_THEME_ID } from "../domain/theme/themeCatalog.js";

export function createEditorState() {
  return {
    session: {
      mode: "read-only",
    },
    document: {
      status: "idle",
      error: null,
      active: null,
    },
    viewport: {
      zoom: 1,
      offsetX: 48,
      offsetY: 48,
      gridVisible: true,
      gridOpacity: 0.25,
      gridColor: "#6f85af",
    },
    interaction: {
      activeTool: "inspect",
      activeLayer: "tiles",
      canvasSelectionMode: "entity",
      activeEntityPresetId: null,
      activeDecorPresetId: null,
      activeSoundPresetId: null,
      activeBackgroundMaterialId: null,
      objectPlacementPreviewSuppressed: false,
      decorScatterMode: false,
      decorScatterSettings: {
        density: 0.3,
        randomness: 0.6,
        variantMode: "fixed",
      },
      hoverCell: null,
      selectedCell: null,
      hoveredEntityIndex: null,
      hoveredEntityId: null,
      hoveredDecorIndex: null,
      hoveredDecorId: null,
      hoveredSoundIndex: null,
      hoveredSoundId: null,
      selectedEntityIndices: [],
      selectedEntityIndex: null,
      selectedEntityIds: [],
      selectedEntityId: null,
      selectedDecorIndices: [],
      selectedDecorIndex: null,
      selectedDecorIds: [],
      selectedDecorId: null,
      selectedSoundIndices: [],
      selectedSoundIndex: null,
      selectedSoundIds: [],
      selectedSoundId: null,
      selectedReactiveGrassPatchIndex: null,
      selectedReactiveGrassPatchId: null,
      selectedReactiveBloomPatchIndex: null,
      selectedReactiveBloomPatchId: null,
      selectedReactiveCrystalPatchIndex: null,
      selectedReactiveCrystalPatchId: null,
      dragPaint: null,
      rectDrag: null,
      lineDrag: null,
      boxSelection: null,
      entityDrag: null,
      decorDrag: null,
      soundDrag: null,
      reactiveDecorType: "grass",
      reactiveGrassPlacementDrag: null,
      reactiveBloomPlacementDrag: null,
      scanDrag: null,
      decorScatterDrag: null,
      spacePanActive: false,
    },
    brush: {
      activeDraft: createDefaultBrushDraft(),
    },
    history: {
      undoStack: [],
      redoStack: [],
      activeBatch: null,
      globalTimeline: createGlobalHistoryTimelineState(),
    },
    scan: {
      playbackState: "idle",
      isPlaying: false,
      speed: 6,
      startX: null,
      endX: null,
      positionX: 0,
      activeSoundIds: [],
      audioEvaluation: {
        previousPositionX: 0,
        positionX: 0,
        activeSoundIds: [],
        startedSoundIds: [],
        endedSoundIds: [],
        activeSounds: [],
        startedSounds: [],
        endedSounds: [],
        transitionEvents: [],
        soundStates: [],
      },
      eventLog: [],
      lastEventSummary: null,
      lastFrameTime: null,
      viewportSnapshot: null,
    },
    soundPreview: {
      playbackState: "idle",
      soundIndex: null,
      soundId: null,
      source: null,
      error: null,
    },
    ui: {
      inspectorOpen: true,
      importStatus: null,
      workspaceBackground: "#0a0f1d",
      darknessPreviewEnabled: false,
      proximityOverlaysEnabled: true,
      topBarMenu: null,
      newLevelSize: {
        isOpen: false,
        width: String(DEFAULT_NEW_LEVEL_WIDTH),
        height: String(DEFAULT_NEW_LEVEL_HEIGHT),
        themeId: DEFAULT_THEME_ID,
        error: null,
      },
      panelSections: {
        tiles: false,
        entities: false,
        decor: false,
        background: false,
        fogVolumes: false,
        sound: false,
      },
      specialVolumeWorkbench: {
        mode: "floating",
        activeType: null,
        openEntityId: null,
        fogDefaults: null,
      },
      assetManager: {
        isOpen: false,
        selectedCategory: "tiles",
        activeView: "wizard",
        wizard: createInitialAssetManagerWizardState(),
      },
    },
  };
}
