import { createDefaultBrushDraft } from "../domain/tiles/brushDraft.js";

export function createEditorState() {
  return {
    session: {
      mode: "read-only",
    },
    document: {
      status: "idle",
      error: null,
      active: null,
    },
    viewport: {
      zoom: 1,
      offsetX: 48,
      offsetY: 48,
      gridVisible: true,
      gridOpacity: 0.25,
      gridColor: "#6f85af",
    },
    interaction: {
      activeTool: "inspect",
      activeLayer: "tiles",
      canvasSelectionMode: "entity",
      activeEntityPresetId: null,
      activeDecorPresetId: null,
      activeSoundPresetId: null,
      decorScatterMode: false,
      decorScatterSettings: {
        density: 0.3,
        randomness: 0.6,
        variantMode: "fixed",
      },
      hoverCell: null,
      selectedCell: null,
      hoveredEntityIndex: null,
      hoveredDecorIndex: null,
      hoveredSoundIndex: null,
      selectedEntityIndices: [],
      selectedEntityIndex: null,
      selectedDecorIndices: [],
      selectedDecorIndex: null,
      selectedSoundIndices: [],
      selectedSoundIndex: null,
      dragPaint: null,
      rectDrag: null,
      lineDrag: null,
      boxSelection: null,
      entityDrag: null,
      decorDrag: null,
      soundDrag: null,
      scanDrag: null,
      decorScatterDrag: null,
      spacePanActive: false,
    },
    brush: {
      activeDraft: createDefaultBrushDraft(),
    },
    history: {
      undoStack: [],
      redoStack: [],
      activeBatch: null,
    },
    scan: {
      playbackState: "idle",
      isPlaying: false,
      speed: 6,
      startX: null,
      endX: null,
      positionX: 0,
      activeSoundIds: [],
      audioEvaluation: {
        previousPositionX: 0,
        positionX: 0,
        activeSoundIds: [],
        startedSoundIds: [],
        endedSoundIds: [],
        activeSounds: [],
        startedSounds: [],
        endedSounds: [],
        transitionEvents: [],
        soundStates: [],
      },
      eventLog: [],
      lastEventSummary: null,
      lastFrameTime: null,
      viewportSnapshot: null,
    },
    soundPreview: {
      playbackState: "idle",
      soundIndex: null,
      soundId: null,
      source: null,
      error: null,
    },
    ui: {
      inspectorOpen: true,
      importStatus: null,
      workspaceBackground: "#0a0f1d",
      darknessPreviewEnabled: false,
      topBarMenu: null,
      panelSections: {
        tools: true,
        layer: true,
        tiles: true,
        entities: true,
        decor: true,
        sound: true,
        scan: true,
      },
    },
  };
}
